### ISSUE TITLE
How to use it with Svelte?

### ISSUE THREAD

**Issue by npupko** [storeon/router#13]
I faced with the problem using this router with Svelte.
It will be awesome to get any instructions or template for this.

**Comment by npupko** [comment]
@ai Thank you in advance

**Comment by ai** [comment]
You need to create `store.js` file with store definition (see `@storeon/svelte` docs). Then you use `connect()` method to get `route`.

In the template, you need to use `router` to render different Svelte page component depends on `route` content.

```js
  import { connect } from "./store.js";
  const { [router.key]: route } = connect(router.key);
```

Will this explanation help you? You can ask @distolma for exact API.

What was the main question for you? How we can improve docs to avoid this question for new developers?

**Comment by npupko** [comment]
@ai In this case I have created `store.js` with:
```js
import { createSvelteStore } from "@storeon/svelte";
import router from '@storeon/router'

export const connect = createSvelteStore([
  router.createRouter([
    ['/', () => ({ page: 'home' })],
    ['/todos', () => ({ page: 'todos' })],
  ])
])
```

and App.svelte with:
```svelte
<script>
  import router from '@storeon/router'
  import { connect } from "./store.js";
  const { [router.key]: route } = connect(router.key);
</script>
Hello {route}
```

But `route` is always `undefined`

**Comment by npupko** [comment]
Looks like the problem in the `const { [router.key]: route } = connect(router.key);` line. It doesn't work at all.
I managed to make it works with `App.svelte`:
```svelte
<script>
  import { connect } from "./store.js";
  import router from '@storeon/router'

  const moduleRouter = connect(router.key)

  const currentPage = () => {
    switch ($moduleRouter.match.page) {
      case "home":
        return import('./routes/Index');
      case "todos":
        return import('./routes/Todos');
      default:
        return "Not found"
    }
  }
</script>

<Navbar/>
{#await currentPage()}
  <p>waiting</p>
{:then result}
  <svelte:component this={result.default || result} />
{:catch error}
  <p>Something went wrong</p>
{/await}
```

**Comment by ai** [comment]
Seems like we need help from @distolma as an author of `@storeon/svelte`.

Or you can look into the compiled version of your components to find the problem.

Maybe we forget to mark variables as dynamical?

**Comment by distolma** [comment]
@npupko I've tried to recreate your [example](https://codesandbox.io/s/gracious-grass-6v9dt) and it seems to be working correctly.

please take a look at an example and inform me about any issues you found.

**Comment by distolma** [comment]
_FYI_ 
you can't destruct `connect` function as 
```javascript
const { [router.key]: route } = connect(router.key);
```
because it contains only `subscribe` and `dispatch` (API 0.4.x).

use the whole object instead, for all reactivity benefits of svelte.

**Comment by npupko** [comment]
@distolma Yep. Thanks. My question has been about destructing.
Maybe it makes sense to add a sample into the README.md file for the new developers?
I have spent a few hours to get access to the store:)
Could I create PR for this?
Something like:

## Usage with Svelte:
If you want to use the router with Svelte you should import the `router.createRouter` from @storeon/router and add this module to `createSvelteStore` instead of `createStore`

`store.js`
```js
import { createSvelteStore } from "@storeon/svelte";
import router from '@storeon/router'
const connect = createSvelteStore([
  router.createRouter([
    ['/', () => ({ page: 'home' })],
    ['/blog', () => ({ page: 'blog' })],
  ])
])
```

And use it like:
`App.svelte`
```svelte
<script>
  import { connect } from "./store.js";
  import router from '@storeon/router'

  const moduleRouter = connect(router.key)
</script>

You can access the router like default svelte store via $:
{$moduleRouter.match.page}
```

**Comment by distolma** [comment]
@npupko yes, it will be good PR for both of packages (how to use `@storeon/svelte` with `@storeon/router` and vice versa)
