### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by ayZagen** [storeon/router#15]
Hello,

Using with svelte and this error occurs when application bundle is injected in `head` tag. Because of [index.js#72](https://github.com/storeon/router/blob/720e7d26412022a5fa0851ec838a7171adba71d7/index.js#L72). I think the event listener should be attached to window instead of body or should be added on window load.

Thanks

**Comment by ai** [comment]
I think we need wrap the block into `if (window)`

**Comment by ivan-solovev** [comment]
Hello! Thank you for the issue. I will fix this bug this weekend.

**Comment by ayZagen** [comment]
> I think we need wrap the block into `if (window)`

`document.body` would be still undefined

**Comment by ivan-solovev** [comment]
Hello. I think the problem is that the document is not ready. Add a DOMContentLoaded listener for document.

**Comment by ayZagen** [comment]
> Hello. I think the problem is that the document is not ready. Add a DOMContentLoaded listener for document.

I think we agree on that so doesn't that mean the library should handle the event ?

**Comment by ivan-solovev** [comment]
Thank you! I fixed that issue.
