### ISSUE TITLE
Make better example

### ISSUE THREAD

**Issue by ai** [storeon/router#2]
Let’s replace `alert('simple')` and `console.log` into something useful.

Second question:

```js
  if (!event.match) {
    // route not found
  }
```

How to use this `event.match`? We need to show it in the example.

**Comment by ivan-solovev** [comment]
1. It is a good idea. I will correct the documentation shortly.
2. Use `event.match` can be used to display 404 page and similar cases where the page does not have a static path

**Comment by ai** [comment]
> Use event.match can be used to display 404 page and similar cases where the page does not have a static path

Can you show an example here?

**Comment by ivan-solovev** [comment]
```
store.on(router.changed, (state, event) => {
  if (!event.match) {
    show404Page()
  }
})
```

**Comment by ai** [comment]
And what is inside `event` data?

**Comment by ivan-solovev** [comment]
```
{
  match: true, // have it found the route?
  path: '/',  // current path
  params: [], // query parameter 
}
```

**Comment by ai** [comment]
And how components will understand what router was matched to render router components?

In my router, routers returns object and component use this data. You can put it to `event.match`.

**Comment by ai** [comment]
Also routers should be able to return `404` as well.

**Comment by ivan-solovev** [comment]
I understood. It is a good idea. Today a bit'll redo router.

**Comment by ai** [comment]
Will we have `match === false` on no router was matched with path?

**Comment by ivan-solovev** [comment]
Yeap. Just moments.

**Comment by ivan-solovev** [comment]
I fixed it.
