### ISSUE TITLE
Manual disable of the onClick handler.

### ISSUE THREAD

**Issue by mrdimidium** [storeon/router#21]
Hey. Thanks for the cool project.!

In my project structure, some references to the current domain, such as /docs, and / logout, are handled on the server, not on the client.

I would like to be able to tell the router that this link should be ignored.

Me seems this can be done 2 ways:
- list of ignored paths in router designer;
- attribute for the link, like data-vanilla, which tells the router that the link does not need to be processed.

What do you think about it?

**Comment by ivan-solovev** [comment]
Hey! That is a good idea. I will think of a better way.

**Comment by ivan-solovev** [comment]
I added `data-ignore-router` attribute to ignore the link.
