### ISSUE TITLE
Problem with anchors with inner elements

### ISSUE THREAD

**Issue by denn1s** [storeon/router#27]
In html, this is valid:
```
<a href="/product/5">
   This <strong>is bold</strong>
</a>
```
However, when using storeon router, clicking the "is bold" fragment causes a full page refresh (the default link behavior). This is especially problematic when using icons or spans in a navigation.

I tried to think a way around it by playing with the eventListener and the bubbling but failed.

**Comment by ivan-solovev** [comment]
Hi! This is a problem. I will try to correct it as soon as possible.
