### ISSUE TITLE
Having Symbols for router events, breaks it in solid-js

### ISSUE THREAD

**Issue by maksimsemenov** [storeon/router#37]
I was trying to use it with [solid-js](https://github.com/ryansolid/solid) through [storeon/solidjs](https://github.com/storeon/solidjs).

However, I faced a problem. When I was trying to dispatch a `routerNavigate` event, it causes an error in the [solid-js state](https://github.com/ryansolid/solid/blob/f400cbea1b8d92c0af870cf46180ac0ef608d930/packages/solid/src/reactive/state.ts#L134):
```
TypeError: Cannot convert a Symbol value to a string
```

Is there any way, to not use Symbols? Maybe just regular strings?

**Comment by ivan-solovev** [comment]
I made the decision to use Symbols so that the router state is separated from the user state.

**Comment by maksimsemenov** [comment]
Oh, ok. I see. But can this be achieved with strings? With something like `storeon-router/navigate`? I think that there is very tiny chance that user will have event with that name.

**Comment by ivan-solovev** [comment]
Still, I don't think it's a good idea. I see other libraries for Storeon use symbols. 😢
