### ISSUE TITLE
Show example of using router in React

### ISSUE THREAD

**Issue by ai** [storeon/router#5]
We need to replace

```js
store.on(router.changed, (state, event) => {
  if (!event.match) {
    show404()
    return
  }

  switch (event.match.page) {
    case 'blog':
      showBlog()
      break
      
    case 'post':
      showPost({
        id: event.match.id,
        year: event.match.year,
        month: event.match.month
      })
      break
      
    default:
      showHome()
  }
})
```

to

```jsx
const Root = () => {
  let page = useStoreon(router.key)
  if (page…) {
    return <Blog>
  } else if …
}
```

**Comment by ai** [comment]
Here is an example that users ask for this https://vk.com/feed?w=wall475146_44097_r44104

**Comment by ivan-solovev** [comment]
Why replace example? It may be better to add under the basic example?

**Comment by ai** [comment]
Because, in the real world, users ask for help because example didn’t help them.

Examples must be closer to real use cases. It is very unlikely that users will use pure JS without Preact, React or Sevlte. Most of Storeon users using React or Preact.

This is why most of Storeon extensions use React examples.

**Comment by ivan-solovev** [comment]
Ok. I'll add the example. But maybe leave the current example to a user who understands the basic work.
What do you think?

**Comment by ai** [comment]
I think the structure of the good doc is:

1. Clear description
2. Copy-parse example
3. Deeper details

If you see a real use case, how this example can be useful for users, you can move it below to the `Details` section.

But I think users just use `useStoreon`. This example will not helpful for them (as we saw in that VK comment).

**Comment by ivan-solovev** [comment]
I'll fix.

**Comment by ivan-solovev** [comment]
I added that example!
